const $ = (id) => document.getElementById(id);
const canvas = $('roastChart'), ctx = canvas.getContext('2d');
let readings = [24, 62, 78, 92, 108, 121, 132, 143, 153, 162, 170, 178, 185];
let events = [{time:'12:00',label:'投豆',detail:'開始吸熱・脫水'},{time:'01:00',label:'回溫點',detail:'BT 62°C，曲線開始上升'},{time:'00:00',label:'預熱完成',detail:'ET 198°C'}];
let step = 1;
const questions = [['先觀察：曲線從哪裡開始改變？','請找出回溫點。它代表探針從環境溫度回到上升的轉折，你猜這個轉折和什麼有關？'],['找證據：哪個階段升溫最快？','比較各段 RoR，哪一段的斜率最陡？這可能如何影響豆子的內部反應？'],['建立連結：一爆前後發生什麼？','一爆是水氣與壓力釋放的聲音。觀察一爆前後的曲線，你會怎麼描述能量變化？'],['形成解釋：你會在哪裡排豆？','根據曲線與你的觀察筆記，提出排豆時機的理由，並預測杯中的風味。']];
function rors(){return readings.map((v,i)=>i?+(v-readings[i-1]).toFixed(1):0)}
function formatMinute(m){return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function draw(){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const p={l:42,r:28,t:18,b:30},cw=w-p.l-p.r,ch=h-p.t-p.b,maxT=Math.max(12,readings.length-1),maxR=Math.max(20,...rors()),x=i=>p.l+i/maxT*cw,y=v=>p.t+ch-(v-20)/210*ch,yr=v=>p.t+ch-v/maxR*ch;ctx.clearRect(0,0,w,h);ctx.font='10px Noto Sans TC';ctx.strokeStyle='#e5dbcf';ctx.fillStyle='#9a9188';for(let i=0;i<=4;i++){let yy=p.t+ch*i/4;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillText(`${220-i*50}°`,4,yy+4)}for(let i=0;i<=6;i++){let xx=p.l+cw*i/6;ctx.beginPath();ctx.moveTo(xx,p.t);ctx.lineTo(xx,h-p.b);ctx.stroke();let min=Math.round(maxT*i/6);ctx.fillText(`${String(min).padStart(2,'0')}:00`,xx-14,h-9)}function line(values,color,map,dash,width){ctx.beginPath();ctx.setLineDash(dash||[]);values.forEach((v,i)=>i?ctx.lineTo(x(i),map(v)):ctx.moveTo(x(i),map(v)));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.setLineDash([])}line(readings,'#bd5b3d',y,[],3);line(readings.map((_,i)=>168-i*1.2),'#7890a0',()=>y(168),[5,4],2);line(rors(),'#798b72',yr,[2,4],1.7);ctx.fillStyle='#bd5b3d';ctx.beginPath();ctx.arc(x(readings.length-1),y(readings.at(-1)),5,0,Math.PI*2);ctx.fill()}
function updateReadouts(){const rs=rors(),last=readings.at(-1),ror=rs.at(-1);$('timeReadout').textContent=formatMinute(readings.length-1);$('btReadout').textContent=last;$('rorReadout').textContent=ror.toFixed(1);$('readingCount').textContent=`${readings.length} READINGS`;$('phaseReadout').textContent=last<100?'脫水':last<180?'梅納反應':'一爆・發展'}
function renderEvents(){$('eventList').innerHTML=events.map(e=>`<div class="event-item"><span class="event-time">${e.time}</span><span class="event-label">${e.label}</span><small>${e.detail}</small></div>`).join('');$('eventCount').textContent=`${events.length} EVENTS`}
$('addReadingBtn').addEventListener('click',()=>{const minute=Number($('minuteInput').value),temp=Number($('manualTemp').value);if(!Number.isFinite(temp)||temp<0||temp>300||!Number.isInteger(minute)||minute<0)return $('manualTemp').focus();while(readings.length<=minute)readings.push(readings.at(-1));readings[minute]=temp;$('minuteInput').value=minute+1;$('manualTemp').value='';updateReadouts();draw()});$('manualTemp').addEventListener('keydown',e=>{if(e.key==='Enter')$('addReadingBtn').click()});
document.querySelectorAll('.event-btn').forEach(btn=>btn.addEventListener('click',()=>{events.unshift({time:formatMinute(readings.length-1),label:btn.dataset.event,detail:`BT ${readings.at(-1)}°C，手動標記`});renderEvents()}));
$('saveInfoBtn').addEventListener('click',()=>{const country=$('countryInput').value||'未填國家',process=$('processInput').value;document.querySelector('.batch-card strong').textContent=`${country}・${process}`;document.querySelector('.batch-card small').textContent=`${$('beanInput').value||'未填品項'} ／ ${$('weatherInput').value||'未填天氣'}・${$('ambientTemp').value}°C・${$('humidityInput').value}% RH`;$('saveInfoBtn').textContent='已儲存 ✓';setTimeout(()=>$('saveInfoBtn').textContent='儲存批次資訊',1800)});
$('nextBtn').addEventListener('click',()=>{step=Math.min(4,step+1);const q=questions[step-1];$('stepCount').textContent=`${step} / 4`;$('stepProgress').style.width=`${step*25}%`;$('questionTitle').textContent=q[0];$('questionText').textContent=q[1];$('hypothesis').value='';if(step===4)$('nextBtn').textContent='完成探究 ✓'});$('hintBtn').addEventListener('click',()=>$('hintText').classList.toggle('visible'));document.querySelectorAll('.tag').forEach(t=>t.addEventListener('click',()=>t.classList.toggle('active')));$('resetBtn').addEventListener('click',()=>location.reload());window.addEventListener('resize',draw);renderEvents();updateReadouts();draw();
